stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: web-blog-buzzgames-me:${CICD_EXECUTION_SEQUENCE} # domain name NOT separated by "." but by "-"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
